export const VEHICLE_CATEGORIES = [
  { label: "Bikes", value: "bike" },
  { label: "Scooty", value: "scooty" },
  { label: "Cars", value: "car" },
  { label: "SUV", value: "suv" },
  { label: "Pickup", value: "pickup" },
  { label: "Truck", value: "truck" },
  { label: "Van", value: "van" },
];

export const VEHICLE_FILTER_OPTIONS = {
  brands: [
    "Mahindra",
    "Maruti Suzuki",
    "Hyundai",
    "Tata",
    "Toyota",
    "Honda",
    "Hero",
    "Honda Bike",
    "Royal Enfield",
    "Yamaha",
    "Bajaj",
    "TVS",
  ],
  cities: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Mamit",
    "Siaha",
    "Lawngtlai",
    "Hnahthial",
    "Saitual",
    "Khawzawl",
  ],
  fuel: ["Petrol", "Diesel", "Electric", "Other"],
  transmission: ["Manual", "Automatic"],
  sort: [
    { label: "Newest", value: "newest" },
    { label: "Price: Low to High", value: "price-asc" },
    { label: "Price: High to Low", value: "price-desc" },
  ],
};
