export const VEHICLE_CATEGORIES = [
  { label: "Bike", value: "Bike" },
  { label: "Scooty", value: "Scooty" },
  { label: "Cars", value: "Car" },
  { label: "SUV", value: "SUV" },
  { label: "Pickup", value: "Pickup" },
  { label: "Truck", value: "Truck" },
  { label: "Van", value: "Van" },
  { label: "Other", value: "Other" },
];

export const VEHICLE_FILTER_OPTIONS = {
  brands: [
    "Mahindra",
    "Maruti Suzuki",
    "Hyundai",
    "Tata",
    "Toyota",
    "Honda",
    "Hero",
    "Honda Bike",
    "Royal Enfield",
    "Yamaha",
    "Bajaj",
    "TVS",
  ],
  cities: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Mamit",
    "Siaha",
    "Lawngtlai",
    "Hnahthial",
    "Saitual",
    "Khawzawl",
  ],
  fuel: ["Petrol", "Diesel", "Electric", "Other"],
  transmission: ["Manual", "Automatic"],
  sort: [
    { label: "Newest", value: "newest" },
    { label: "Price: Low to High", value: "price-asc" },
    { label: "Price: High to Low", value: "price-desc" },
  ],
};
